---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    app: prometheus
  name: prometheus-ingress
  namespace: monitoring
spec:
  defaultBackend:
    service:
      name: prometheus-kube-prometheus-prometheus
      port:
        number: 9090
  rules:
    - host: prometheus.{{ .Values.hostname }}
      http:
        paths:
          - backend:
              service:
                name: prometheus-kube-prometheus-prometheus
                port:
                  number: 9090
            path: /
            pathType: ImplementationSpecific
