apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    # allow more response header size when a session expires
    nginx.ingress.kubernetes.io/proxy-buffer-size: "16k"
    route.openshift.io/termination: passthrough
  labels:
    app: keycloak
  name: keycloak-ingress
  namespace: keycloak
spec:
  tls:
    - hosts:
        - keycloak.{{ .Values.hostname }}
      secretName: keycloak-tls-secret
  defaultBackend:
    service:
      name: keycloak-service
      port:
        number: 8443
  rules:
  - host: keycloak.{{ .Values.hostname }}
    http:
      paths:
      - backend:
          service:
            name: keycloak-service
            port:
              number: 8443
        pathType: ImplementationSpecific
